services:
  api:
    container_name: voltr-api
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    environment:
      VOLTR_API_ADDRESS: ":8080"
      DB_HOST: postgres
      DB_PORT: "5432"
      ENVIRONMENT: prd
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/live"]
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: ghcr.io/amacneil/dbmate
    command: ["up"]
    volumes:
      - ./db:/db:rw
    env_file:
      - .env.dbmate
    networks:
      - postgres-network
    profiles:
      - migrate

networks:
  postgres-network:
    external: true
