// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID          int64              `json:"id"`
	UserID      *int64             `json:"userId"`
	HouseholdID *int64             `json:"householdId"`
	Type        string             `json:"type"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type BudgetCategory struct {
	ID           int64              `json:"id"`
	BudgetID     *int64             `json:"budgetId"`
	CategoryName string             `json:"categoryName"`
	Allocation   float32            `json:"allocation"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Household struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	GuildID   string             `json:"guildId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type HouseholdUser struct {
	HouseholdID int64              `json:"householdId"`
	UserID      int64              `json:"userId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type LlmMessage struct {
	ID        int64              `json:"id"`
	SessionID int64              `json:"sessionId"`
	ParentID  *int64             `json:"parentId"`
	Role      string             `json:"role"`
	Contents  []byte             `json:"contents"`
	UserID    int64              `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type LlmSession struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	SourceID  string             `json:"sourceId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Transaction struct {
	ID               int64              `json:"id"`
	Amount           float32            `json:"amount"`
	AuthorID         int64              `json:"authorId"`
	BudgetCategoryID *int64             `json:"budgetCategoryId"`
	Description      *string            `json:"description"`
	TransactionDate  pgtype.Timestamptz `json:"transactionDate"`
	TransactionID    string             `json:"transactionId"`
	HouseholdID      *int64             `json:"householdId"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID        int64              `json:"id"`
	DiscordID string             `json:"discordId"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
