// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Defines a financial plan, which can be assigned to either an individual or a household.
type Budget struct {
	// Internal unique identifier for the budget.
	ID int64 `json:"id"`
	// Optional reference to a specific user for personal budgets.
	UserID *int64 `json:"userId"`
	// Optional reference to a household for shared group budgets.
	HouseholdID    *int64             `json:"householdId"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	PeriodStart    pgtype.Date        `json:"periodStart"`
	PeriodEnd      pgtype.Date        `json:"periodEnd"`
	SourceBudgetID *int64             `json:"sourceBudgetId"`
}

type BudgetLine struct {
	ID               int64              `json:"id"`
	BudgetID         int64              `json:"budgetId"`
	Name             string             `json:"name"`
	AllocationAmount pgtype.Numeric     `json:"allocationAmount"`
	SortOrder        int32              `json:"sortOrder"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
}

type BudgetLineCategory struct {
	BudgetID     int64              `json:"budgetId"`
	BudgetLineID int64              `json:"budgetLineId"`
	CategoryID   int64              `json:"categoryId"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type Category struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsActive    bool               `json:"isActive"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

// Groups users together into a shared financial unit, linked to a Discord server.
type Household struct {
	// Internal unique identifier for the household.
	ID int64 `json:"id"`
	// A unique human-readable name for the household group.
	Name string `json:"name"`
	// The Discord Guild (server) ID associated with this household.
	GuildID string `json:"guildId"`
	// Timestamp when the household was established.
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	// Timestamp of the last update to household metadata.
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

// A join table representing the many-to-many relationship between users and households.
type HouseholdUser struct {
	// Reference to the household.
	HouseholdID int64 `json:"householdId"`
	// Reference to the user.
	UserID int64 `json:"userId"`
	// Timestamp when the user joined the household.
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	// Timestamp of the last change to this membership record.
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type LlmMessage struct {
	ID        int64              `json:"id"`
	SessionID int64              `json:"sessionId"`
	ParentID  *int64             `json:"parentId"`
	Role      string             `json:"role"`
	Contents  []byte             `json:"contents"`
	UserID    int64              `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type LlmSession struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	SourceID  string             `json:"sourceId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

// Records individual financial movements including amount, author, and categorization.
type Transaction struct {
	// Internal unique identifier for the transaction.
	ID int64 `json:"id"`
	// The numerical value of the transaction. If positive, it indicates an expense; if negative, income.
	Amount float32 `json:"amount"`
	// The user who created or is responsible for the transaction.
	AuthorID int64 `json:"authorId"`
	// A short summary of the transaction purpose.
	Description *string `json:"description"`
	// The actual date and time the financial event occurred.
	TransactionDate pgtype.Timestamptz `json:"transactionDate"`
	// A unique hash or external identifier to prevent duplicate entries.
	TransactionID string `json:"transactionId"`
	// The household context in which this transaction took place.
	HouseholdID *int64 `json:"householdId"`
	// Extended details or commentary regarding the transaction.
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	DeletedByUserID *int64             `json:"deletedByUserId"`
	DeleteReason    *string            `json:"deleteReason"`
	CategoryID      *int64             `json:"categoryId"`
}

// Stores identity information for individuals linked to Discord accounts.
type User struct {
	// Internal unique identifier for the user.
	ID int64 `json:"id"`
	// The unique ID provided by the Discord API.
	DiscordID *string `json:"discordId"`
	// The display name or username of the Discord user.
	Name string `json:"name"`
	// Timestamp when the user record was first created.
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	// Timestamp of the most recent modification to the user record.
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	TelegramID  *string            `json:"telegramId"`
	PhoneNumber *string            `json:"phoneNumber"`
	WhatsappID  *string            `json:"whatsappId"`
}
