// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetLine = `-- name: CreateBudgetLine :one
INSERT INTO budget_line (budget_id, name, allocation_amount, sort_order)
VALUES (
    $1::BIGINT,
    $2::VARCHAR,
    $3::NUMERIC,
    $4::INTEGER
)
RETURNING id, budget_id, name, allocation_amount, sort_order, created_at, updated_at
`

type CreateBudgetLineParams struct {
	BudgetID         int64          `json:"budgetId"`
	Name             string         `json:"name"`
	AllocationAmount pgtype.Numeric `json:"allocationAmount"`
	SortOrder        int32          `json:"sortOrder"`
}

func (q *Queries) CreateBudgetLine(ctx context.Context, arg CreateBudgetLineParams) (BudgetLine, error) {
	row := q.db.QueryRow(ctx, createBudgetLine,
		arg.BudgetID,
		arg.Name,
		arg.AllocationAmount,
		arg.SortOrder,
	)
	var i BudgetLine
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.Name,
		&i.AllocationAmount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBudgetLineCategory = `-- name: CreateBudgetLineCategory :exec
INSERT INTO budget_line_category (budget_id, budget_line_id, category_id)
VALUES (
    $1::BIGINT,
    $2::BIGINT,
    $3::BIGINT
)
`

type CreateBudgetLineCategoryParams struct {
	BudgetID     int64 `json:"budgetId"`
	BudgetLineID int64 `json:"budgetLineId"`
	CategoryID   int64 `json:"categoryId"`
}

func (q *Queries) CreateBudgetLineCategory(ctx context.Context, arg CreateBudgetLineCategoryParams) error {
	_, err := q.db.Exec(ctx, createBudgetLineCategory, arg.BudgetID, arg.BudgetLineID, arg.CategoryID)
	return err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO category (code, name, description)
VALUES ($1, $2, $3)
RETURNING id, code, name, description, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

// ******************* category *******************
// WRITES
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Code, arg.Name, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHouseholdBudget = `-- name: CreateHouseholdBudget :one

INSERT INTO budget (household_id, user_id, period_start, period_end, source_budget_id)
VALUES (
    $1::BIGINT,
    NULL,
    $2::DATE,
    $3::DATE,
    $4::BIGINT
)
RETURNING id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id
`

type CreateHouseholdBudgetParams struct {
	HouseholdID    int64       `json:"householdId"`
	PeriodStart    pgtype.Date `json:"periodStart"`
	PeriodEnd      pgtype.Date `json:"periodEnd"`
	SourceBudgetID *int64      `json:"sourceBudgetId"`
}

// WRITES
func (q *Queries) CreateHouseholdBudget(ctx context.Context, arg CreateHouseholdBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createHouseholdBudget,
		arg.HouseholdID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SourceBudgetID,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const createLlmMessage = `-- name: CreateLlmMessage :one
INSERT INTO
    llm_message (session_id, user_id, role, contents, parent_id)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateLlmMessageParams struct {
	SessionID int64  `json:"sessionId"`
	UserID    int64  `json:"userId"`
	Role      string `json:"role"`
	Contents  []byte `json:"contents"`
	ParentID  *int64 `json:"parentId"`
}

// Messages
func (q *Queries) CreateLlmMessage(ctx context.Context, arg CreateLlmMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLlmMessage,
		arg.SessionID,
		arg.UserID,
		arg.Role,
		arg.Contents,
		arg.ParentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLlmSession = `-- name: CreateLlmSession :one
INSERT INTO
    llm_session (user_id, source_id)
VALUES
    ($1, $2) RETURNING id, user_id, source_id, created_at, updated_at
`

type CreateLlmSessionParams struct {
	UserID   int64  `json:"userId"`
	SourceID string `json:"sourceId"`
}

// ******************* LLM *******************
// Session
func (q *Queries) CreateLlmSession(ctx context.Context, arg CreateLlmSessionParams) (LlmSession, error) {
	row := q.db.QueryRow(ctx, createLlmSession, arg.UserID, arg.SourceID)
	var i LlmSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transaction
(
    amount,
    category_id,
    description,
    transaction_date,
    transaction_id,
    author_id,
    household_id,
    notes
)
VALUES
($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id
`

type CreateTransactionParams struct {
	Amount          float32            `json:"amount"`
	CategoryID      *int64             `json:"categoryId"`
	Description     *string            `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transactionDate"`
	TransactionID   string             `json:"transactionId"`
	AuthorID        int64              `json:"authorId"`
	HouseholdID     *int64             `json:"householdId"`
	Notes           *string            `json:"notes"`
}

// WRITES
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.CategoryID,
		arg.Description,
		arg.TransactionDate,
		arg.TransactionID,
		arg.AuthorID,
		arg.HouseholdID,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
		&i.CategoryID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (discord_id, telegram_id, phone_number, whatsapp_id, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id
`

type CreateUserParams struct {
	DiscordID   *string `json:"discordId"`
	TelegramID  *string `json:"telegramId"`
	PhoneNumber *string `json:"phoneNumber"`
	WhatsappID  *string `json:"whatsappId"`
	Name        string  `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DiscordID,
		arg.TelegramID,
		arg.PhoneNumber,
		arg.WhatsappID,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const createUserBudget = `-- name: CreateUserBudget :one
INSERT INTO budget (household_id, user_id, period_start, period_end, source_budget_id)
VALUES (
    NULL,
    $1::BIGINT,
    $2::DATE,
    $3::DATE,
    $4::BIGINT
)
RETURNING id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id
`

type CreateUserBudgetParams struct {
	UserID         int64       `json:"userId"`
	PeriodStart    pgtype.Date `json:"periodStart"`
	PeriodEnd      pgtype.Date `json:"periodEnd"`
	SourceBudgetID *int64      `json:"sourceBudgetId"`
}

func (q *Queries) CreateUserBudget(ctx context.Context, arg CreateUserBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createUserBudget,
		arg.UserID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SourceBudgetID,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :one
UPDATE category
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE code = $1
RETURNING id, code, name, description, is_active, created_at, updated_at
`

func (q *Queries) DeactivateCategory(ctx context.Context, code string) (Category, error) {
	row := q.db.QueryRow(ctx, deactivateCategory, code)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudgetLine = `-- name: DeleteBudgetLine :exec
DELETE FROM budget_line
WHERE id = $1::BIGINT
`

func (q *Queries) DeleteBudgetLine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBudgetLine, id)
	return err
}

const deleteBudgetLineCategories = `-- name: DeleteBudgetLineCategories :exec
DELETE FROM budget_line_category
WHERE budget_line_id = $1::BIGINT
`

func (q *Queries) DeleteBudgetLineCategories(ctx context.Context, budgetLineID int64) error {
	_, err := q.db.Exec(ctx, deleteBudgetLineCategories, budgetLineID)
	return err
}

const getActiveCategoryByCode = `-- name: GetActiveCategoryByCode :one
SELECT id, code, name, description, is_active, created_at, updated_at FROM category
WHERE code = $1 AND is_active
`

func (q *Queries) GetActiveCategoryByCode(ctx context.Context, code string) (Category, error) {
	row := q.db.QueryRow(ctx, getActiveCategoryByCode, code)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCategoryById = `-- name: GetActiveCategoryById :one
SELECT id, code, name, description, is_active, created_at, updated_at FROM category
WHERE id = $1 AND is_active
`

func (q *Queries) GetActiveCategoryById(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getActiveCategoryById, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionBySourceId = `-- name: GetActiveSessionBySourceId :one
SELECT
    id, user_id, source_id, created_at, updated_at
FROM
    llm_session
WHERE
    source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetActiveSessionBySourceId(ctx context.Context, sourceID string) (LlmSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionBySourceId, sourceID)
	var i LlmSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetById = `-- name: GetBudgetById :one
SELECT id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id FROM budget
WHERE id = $1::BIGINT
`

func (q *Queries) GetBudgetById(ctx context.Context, id int64) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetById, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const getBudgetLineById = `-- name: GetBudgetLineById :one
SELECT id, budget_id, name, allocation_amount, sort_order, created_at, updated_at FROM budget_line
WHERE id = $1::BIGINT
`

func (q *Queries) GetBudgetLineById(ctx context.Context, id int64) (BudgetLine, error) {
	row := q.db.QueryRow(ctx, getBudgetLineById, id)
	var i BudgetLine
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.Name,
		&i.AllocationAmount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByCode = `-- name: GetCategoryByCode :one
SELECT id, code, name, description, is_active, created_at, updated_at FROM category
WHERE code = $1
`

func (q *Queries) GetCategoryByCode(ctx context.Context, code string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByCode, code)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, code, name, description, is_active, created_at, updated_at FROM category
WHERE id = $1
`

func (q *Queries) GetCategoryById(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdBudgetByPeriod = `-- name: GetHouseholdBudgetByPeriod :one

SELECT id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id FROM budget
WHERE household_id = $1::BIGINT
  AND user_id IS NULL
  AND period_start = $2::DATE
  AND period_end = $3::DATE
`

type GetHouseholdBudgetByPeriodParams struct {
	HouseholdID int64       `json:"householdId"`
	PeriodStart pgtype.Date `json:"periodStart"`
	PeriodEnd   pgtype.Date `json:"periodEnd"`
}

// ******************* budget *******************
// READS
func (q *Queries) GetHouseholdBudgetByPeriod(ctx context.Context, arg GetHouseholdBudgetByPeriodParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getHouseholdBudgetByPeriod, arg.HouseholdID, arg.PeriodStart, arg.PeriodEnd)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const getHouseholdByGuildId = `-- name: GetHouseholdByGuildId :one
SELECT id, name, guild_id, created_at, updated_at from household where guild_id = $1
`

func (q *Queries) GetHouseholdByGuildId(ctx context.Context, guildID string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByGuildId, guildID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GuildID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdById = `-- name: GetHouseholdById :one
SELECT id, name, guild_id, created_at, updated_at FROM household WHERE id = $1
`

func (q *Queries) GetHouseholdById(ctx context.Context, id int64) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdById, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GuildID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByName = `-- name: GetHouseholdByName :one
SELECT id, name, guild_id, created_at, updated_at FROM household WHERE name = $1
`

func (q *Queries) GetHouseholdByName(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByName, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GuildID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdUsers = `-- name: GetHouseholdUsers :many
SELECT u.id, u.discord_id, u.name, u.created_at, u.updated_at, u.telegram_id, u.phone_number, u.whatsapp_id FROM users u
JOIN household_user hu on hu.user_id = u.id
WHERE hu.household_id = $1
`

func (q *Queries) GetHouseholdUsers(ctx context.Context, householdID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getHouseholdUsers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramID,
			&i.PhoneNumber,
			&i.WhatsappID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdByTransactionId = `-- name: GetIdByTransactionId :one
SELECT id FROM transaction
WHERE transaction_id = $1
`

func (q *Queries) GetIdByTransactionId(ctx context.Context, transactionID string) (int64, error) {
	row := q.db.QueryRow(ctx, getIdByTransactionId, transactionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLatestPriorHouseholdBudget = `-- name: GetLatestPriorHouseholdBudget :one
SELECT id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id FROM budget
WHERE household_id = $1::BIGINT
  AND user_id IS NULL
  AND period_start < $2::DATE
ORDER BY period_start DESC, id DESC
LIMIT 1
`

type GetLatestPriorHouseholdBudgetParams struct {
	HouseholdID int64       `json:"householdId"`
	PeriodStart pgtype.Date `json:"periodStart"`
}

func (q *Queries) GetLatestPriorHouseholdBudget(ctx context.Context, arg GetLatestPriorHouseholdBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getLatestPriorHouseholdBudget, arg.HouseholdID, arg.PeriodStart)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const getLatestPriorUserBudget = `-- name: GetLatestPriorUserBudget :one
SELECT id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id FROM budget
WHERE user_id = $1::BIGINT
  AND household_id IS NULL
  AND period_start < $2::DATE
ORDER BY period_start DESC, id DESC
LIMIT 1
`

type GetLatestPriorUserBudgetParams struct {
	UserID      int64       `json:"userId"`
	PeriodStart pgtype.Date `json:"periodStart"`
}

func (q *Queries) GetLatestPriorUserBudget(ctx context.Context, arg GetLatestPriorUserBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getLatestPriorUserBudget, arg.UserID, arg.PeriodStart)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const getMaxBudgetLineSortOrder = `-- name: GetMaxBudgetLineSortOrder :one
SELECT COALESCE(MAX(sort_order), 0)::INTEGER AS sort_order
FROM budget_line
WHERE budget_id = $1::BIGINT
`

func (q *Queries) GetMaxBudgetLineSortOrder(ctx context.Context, budgetID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxBudgetLineSortOrder, budgetID)
	var sort_order int32
	err := row.Scan(&sort_order)
	return sort_order, err
}

const getTableAndColumnMetadata = `-- name: GetTableAndColumnMetadata :many

SELECT
  t.table_schema::text AS schema_name,
  t.table_name::text AS table_name,
  COALESCE(obj_description(pgc.oid, 'pg_class'), '')::text AS table_description,
  c.column_name::text AS column_name,
  c.data_type::text AS data_type,
  COALESCE(col_description(pgc.oid, c.ordinal_position), '')::text AS column_description,
  (c.is_nullable = 'YES')::boolean AS is_nullable,
  -- Check if part of any index
  EXISTS (
    SELECT 1
    FROM pg_catalog.pg_index i
    WHERE i.indrelid = pgc.oid
      AND c.ordinal_position = ANY(i.indkey)
  )::boolean AS is_indexed,
  -- Check if part of a unique index
  EXISTS (
    SELECT 1
    FROM pg_catalog.pg_index i
    WHERE i.indrelid = pgc.oid
      AND i.indisunique = true
      AND c.ordinal_position = ANY(i.indkey)
  )::boolean AS is_unique,
  -- 1. Foreign Key in format table.column
  COALESCE(
    (
      SELECT ta.relname || '.' || fa.attname
      FROM pg_catalog.pg_constraint con
      JOIN pg_catalog.pg_class ta ON con.confrelid = ta.oid
      JOIN pg_catalog.pg_attribute fa ON fa.attrelid = con.confrelid AND fa.attnum = ANY(con.confkey)
      WHERE con.conrelid = pgc.oid
        AND con.contype = 'f'
        AND c.ordinal_position = ANY(con.conkey)
      LIMIT 1
    ),
    ''
  )::text AS foreign_key_target,
  -- 3. Primary Key Identity
  EXISTS (
    SELECT 1
    FROM pg_catalog.pg_constraint con
    WHERE con.conrelid = pgc.oid
      AND con.contype = 'p'
      AND c.ordinal_position = ANY(con.conkey)
  )::boolean AS is_primary_key
FROM
  information_schema.tables t
  JOIN pg_catalog.pg_class pgc ON t.table_name = pgc.relname
  JOIN pg_catalog.pg_namespace pgn ON pgc.relnamespace = pgn.oid
  AND t.table_schema = pgn.nspname
  JOIN information_schema.columns c ON t.table_name = c.table_name
  AND t.table_schema = c.table_schema
WHERE
  t.table_schema = 'transactions'
  AND t.table_name = ANY($1::TEXT[])
ORDER BY
  t.table_name,
  c.ordinal_position
`

type GetTableAndColumnMetadataRow struct {
	SchemaName        string `json:"schemaName"`
	TableName         string `json:"tableName"`
	TableDescription  string `json:"tableDescription"`
	ColumnName        string `json:"columnName"`
	DataType          string `json:"dataType"`
	ColumnDescription string `json:"columnDescription"`
	IsNullable        bool   `json:"isNullable"`
	IsIndexed         bool   `json:"isIndexed"`
	IsUnique          bool   `json:"isUnique"`
	ForeignKeyTarget  string `json:"foreignKeyTarget"`
	IsPrimaryKey      bool   `json:"isPrimaryKey"`
}

// ******************* sql metadata *******************
func (q *Queries) GetTableAndColumnMetadata(ctx context.Context, tableNames []string) ([]GetTableAndColumnMetadataRow, error) {
	rows, err := q.db.Query(ctx, getTableAndColumnMetadata, tableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableAndColumnMetadataRow
	for rows.Next() {
		var i GetTableAndColumnMetadataRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.TableDescription,
			&i.ColumnName,
			&i.DataType,
			&i.ColumnDescription,
			&i.IsNullable,
			&i.IsIndexed,
			&i.IsUnique,
			&i.ForeignKeyTarget,
			&i.IsPrimaryKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionById = `-- name: GetTransactionById :one

SELECT id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id FROM transaction
WHERE id = $1
`

// ******************* transaction *******************
// READS
func (q *Queries) GetTransactionById(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
		&i.CategoryID,
	)
	return i, err
}

const getTransactionByIdActive = `-- name: GetTransactionByIdActive :one
SELECT id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id FROM transaction
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByIdActive(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdActive, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
		&i.CategoryID,
	)
	return i, err
}

const getTransactionsById = `-- name: GetTransactionsById :many
SELECT id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id FROM transaction
WHERE id = ANY($1::BIGINT[])
`

func (q *Queries) GetTransactionsById(ctx context.Context, ids []int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsById, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByIdActive = `-- name: GetTransactionsByIdActive :many
SELECT id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id FROM transaction
WHERE id = ANY($1::BIGINT[])
  AND deleted_at IS NULL
`

func (q *Queries) GetTransactionsByIdActive(ctx context.Context, ids []int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByIdActive, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByIdWithDetails = `-- name: GetTransactionsByIdWithDetails :many
SELECT
    t.id, t.amount, t.author_id, t.description, t.transaction_date, t.transaction_id, t.household_id, t.notes, t.created_at, t.updated_at, t.deleted_at, t.deleted_by_user_id, t.delete_reason, t.category_id,
    u.id AS author_id,
    u.name AS author_name,
    h.id AS household_id,
    h.name AS household_name,
    c.id AS category_id,
    c.code AS category_code,
    c.name AS category_name
FROM transaction t
JOIN users u ON u.id = t.author_id
LEFT JOIN household h ON h.id = t.household_id
LEFT JOIN category c ON c.id = t.category_id
WHERE t.id = ANY($1::BIGINT[])
  AND ($2::bool OR t.deleted_at IS NULL)
ORDER BY array_position($1::BIGINT[], t.id)
`

type GetTransactionsByIdWithDetailsParams struct {
	Ids            []int64 `json:"ids"`
	IncludeDeleted bool    `json:"includeDeleted"`
}

type GetTransactionsByIdWithDetailsRow struct {
	Transaction   Transaction `json:"transaction"`
	AuthorID      int64       `json:"authorId"`
	AuthorName    string      `json:"authorName"`
	HouseholdID   *int64      `json:"householdId"`
	HouseholdName *string     `json:"householdName"`
	CategoryID    *int64      `json:"categoryId"`
	CategoryCode  *string     `json:"categoryCode"`
	CategoryName  *string     `json:"categoryName"`
}

func (q *Queries) GetTransactionsByIdWithDetails(ctx context.Context, arg GetTransactionsByIdWithDetailsParams) ([]GetTransactionsByIdWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByIdWithDetails, arg.Ids, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByIdWithDetailsRow
	for rows.Next() {
		var i GetTransactionsByIdWithDetailsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.Amount,
			&i.Transaction.AuthorID,
			&i.Transaction.Description,
			&i.Transaction.TransactionDate,
			&i.Transaction.TransactionID,
			&i.Transaction.HouseholdID,
			&i.Transaction.Notes,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.DeletedAt,
			&i.Transaction.DeletedByUserID,
			&i.Transaction.DeleteReason,
			&i.Transaction.CategoryID,
			&i.AuthorID,
			&i.AuthorName,
			&i.HouseholdID,
			&i.HouseholdName,
			&i.CategoryID,
			&i.CategoryCode,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBudgetByPeriod = `-- name: GetUserBudgetByPeriod :one
SELECT id, user_id, household_id, created_at, updated_at, period_start, period_end, source_budget_id FROM budget
WHERE user_id = $1::BIGINT
  AND household_id IS NULL
  AND period_start = $2::DATE
  AND period_end = $3::DATE
`

type GetUserBudgetByPeriodParams struct {
	UserID      int64       `json:"userId"`
	PeriodStart pgtype.Date `json:"periodStart"`
	PeriodEnd   pgtype.Date `json:"periodEnd"`
}

func (q *Queries) GetUserBudgetByPeriod(ctx context.Context, arg GetUserBudgetByPeriodParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getUserBudgetByPeriod, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SourceBudgetID,
	)
	return i, err
}

const getUserByDiscordAndHouseholdId = `-- name: GetUserByDiscordAndHouseholdId :one
SELECT u.id, u.discord_id, u.name, u.created_at, u.updated_at, u.telegram_id, u.phone_number, u.whatsapp_id FROM users u
JOIN household_user hu on hu.user_id = u.id
WHERE discord_id = $1 and hu.household_id = $2
`

type GetUserByDiscordAndHouseholdIdParams struct {
	DiscordID   *string `json:"discordId"`
	HouseholdID int64   `json:"householdId"`
}

func (q *Queries) GetUserByDiscordAndHouseholdId(ctx context.Context, arg GetUserByDiscordAndHouseholdIdParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordAndHouseholdId, arg.DiscordID, arg.HouseholdID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByDiscordId = `-- name: GetUserByDiscordId :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordId(ctx context.Context, discordID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordId, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByTelegramId = `-- name: GetUserByTelegramId :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramId(ctx context.Context, telegramID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramId, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByWhatsappId = `-- name: GetUserByWhatsappId :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE whatsapp_id = $1
`

func (q *Queries) GetUserByWhatsappId(ctx context.Context, whatsappID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWhatsappId, whatsappID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserDetailsByDiscordId = `-- name: GetUserDetailsByDiscordId :one

SELECT users.id, users.discord_id, users.name, users.created_at, users.updated_at, users.telegram_id, users.phone_number, users.whatsapp_id, household.id, household.name, household.guild_id, household.created_at, household.updated_at FROM users
JOIN household_user on users.id = household_user.user_id
JOIN household on household_user.household_id = household.id
WHERE users.discord_id = $1
`

type GetUserDetailsByDiscordIdRow struct {
	User      User      `json:"user"`
	Household Household `json:"household"`
}

// ******************* users *******************
// READS
func (q *Queries) GetUserDetailsByDiscordId(ctx context.Context, discordID *string) (GetUserDetailsByDiscordIdRow, error) {
	row := q.db.QueryRow(ctx, getUserDetailsByDiscordId, discordID)
	var i GetUserDetailsByDiscordIdRow
	err := row.Scan(
		&i.User.ID,
		&i.User.DiscordID,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.TelegramID,
		&i.User.PhoneNumber,
		&i.User.WhatsappID,
		&i.Household.ID,
		&i.Household.Name,
		&i.Household.GuildID,
		&i.Household.CreatedAt,
		&i.Household.UpdatedAt,
	)
	return i, err
}

const listBudgetLineCategories = `-- name: ListBudgetLineCategories :many
SELECT
    blc.budget_id,
    blc.budget_line_id,
    blc.category_id,
    c.code AS category_code,
    c.name AS category_name
FROM budget_line_category blc
JOIN category c ON c.id = blc.category_id
WHERE blc.budget_id = $1::BIGINT
ORDER BY blc.budget_line_id ASC, c.name ASC, c.id ASC
`

type ListBudgetLineCategoriesRow struct {
	BudgetID     int64  `json:"budgetId"`
	BudgetLineID int64  `json:"budgetLineId"`
	CategoryID   int64  `json:"categoryId"`
	CategoryCode string `json:"categoryCode"`
	CategoryName string `json:"categoryName"`
}

func (q *Queries) ListBudgetLineCategories(ctx context.Context, budgetID int64) ([]ListBudgetLineCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetLineCategories, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetLineCategoriesRow
	for rows.Next() {
		var i ListBudgetLineCategoriesRow
		if err := rows.Scan(
			&i.BudgetID,
			&i.BudgetLineID,
			&i.CategoryID,
			&i.CategoryCode,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetLines = `-- name: ListBudgetLines :many
SELECT id, budget_id, name, allocation_amount, sort_order, created_at, updated_at FROM budget_line
WHERE budget_id = $1::BIGINT
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListBudgetLines(ctx context.Context, budgetID int64) ([]BudgetLine, error) {
	rows, err := q.db.Query(ctx, listBudgetLines, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetLine
	for rows.Next() {
		var i BudgetLine
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.Name,
			&i.AllocationAmount,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetReportLines = `-- name: ListBudgetReportLines :many
SELECT
    bl.id,
    bl.budget_id,
    bl.name,
    bl.allocation_amount,
    ROUND(COALESCE(SUM(t.amount), 0)::NUMERIC, 2) AS actual_amount,
    bl.sort_order
FROM budget b
JOIN budget_line bl ON bl.budget_id = b.id
LEFT JOIN budget_line_category blc
    ON blc.budget_id = b.id
   AND blc.budget_line_id = bl.id
LEFT JOIN transaction t
    ON t.deleted_at IS NULL
   AND t.category_id = blc.category_id
   AND t.transaction_date >= (b.period_start::DATE::TIMESTAMP AT TIME ZONE 'UTC')
   AND t.transaction_date < ((b.period_end::DATE + INTERVAL '1 day')::TIMESTAMP AT TIME ZONE 'UTC')
   AND (
       (b.household_id IS NOT NULL AND t.household_id = b.household_id)
       OR
       (b.user_id IS NOT NULL AND t.author_id = b.user_id AND t.household_id IS NULL)
   )
WHERE b.id = $1::BIGINT
GROUP BY bl.id, bl.budget_id, bl.name, bl.allocation_amount, bl.sort_order
ORDER BY bl.sort_order ASC, bl.id ASC
`

type ListBudgetReportLinesRow struct {
	ID               int64          `json:"id"`
	BudgetID         int64          `json:"budgetId"`
	Name             string         `json:"name"`
	AllocationAmount pgtype.Numeric `json:"allocationAmount"`
	ActualAmount     pgtype.Numeric `json:"actualAmount"`
	SortOrder        int32          `json:"sortOrder"`
}

func (q *Queries) ListBudgetReportLines(ctx context.Context, budgetID int64) ([]ListBudgetReportLinesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetReportLines, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetReportLinesRow
	for rows.Next() {
		var i ListBudgetReportLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.Name,
			&i.AllocationAmount,
			&i.ActualAmount,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many

SELECT id, code, name, description, is_active, created_at, updated_at FROM category
WHERE ($1::bool OR is_active)
ORDER BY name ASC, id ASC
`

// READS
func (q *Queries) ListCategories(ctx context.Context, includeInactive bool) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, includeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholds = `-- name: ListHouseholds :many
SELECT id, name, guild_id, created_at, updated_at FROM household
ORDER BY name ASC, id ASC
`

func (q *Queries) ListHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GuildID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLlmMessagesBySessionId = `-- name: ListLlmMessagesBySessionId :many
SELECT
    m.id, m.session_id, m.parent_id, m.role, m.contents, m.user_id, m.created_at, m.updated_at, u.id, u.discord_id, u.name, u.created_at, u.updated_at, u.telegram_id, u.phone_number, u.whatsapp_id
FROM
    llm_message m
JOIN
    users u on u.id = m.user_id
WHERE
    m.session_id = $1
ORDER BY
    m.created_at ASC
`

type ListLlmMessagesBySessionIdRow struct {
	LlmMessage LlmMessage `json:"llmMessage"`
	User       User       `json:"user"`
}

func (q *Queries) ListLlmMessagesBySessionId(ctx context.Context, sessionID int64) ([]ListLlmMessagesBySessionIdRow, error) {
	rows, err := q.db.Query(ctx, listLlmMessagesBySessionId, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLlmMessagesBySessionIdRow
	for rows.Next() {
		var i ListLlmMessagesBySessionIdRow
		if err := rows.Scan(
			&i.LlmMessage.ID,
			&i.LlmMessage.SessionID,
			&i.LlmMessage.ParentID,
			&i.LlmMessage.Role,
			&i.LlmMessage.Contents,
			&i.LlmMessage.UserID,
			&i.LlmMessage.CreatedAt,
			&i.LlmMessage.UpdatedAt,
			&i.User.ID,
			&i.User.DiscordID,
			&i.User.Name,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.TelegramID,
			&i.User.PhoneNumber,
			&i.User.WhatsappID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id, t.amount, t.author_id, t.description, t.transaction_date, t.transaction_id, t.household_id, t.notes, t.created_at, t.updated_at, t.deleted_at, t.deleted_by_user_id, t.delete_reason, t.category_id,
    u.id AS author_id,
    u.name AS author_name,
    h.id AS household_id,
    h.name AS household_name,
    c.id AS category_id,
    c.code AS category_code,
    c.name AS category_name
FROM transaction t
JOIN users u ON u.id = t.author_id
LEFT JOIN household h ON h.id = t.household_id
LEFT JOIN category c ON c.id = t.category_id
WHERE
    (NOT $1::bool OR t.deleted_at IS NOT NULL)
    AND ($2::bool OR $1::bool OR t.deleted_at IS NULL)
    AND ($3::BIGINT IS NULL OR t.author_id = $3::BIGINT)
    AND ($4::BIGINT IS NULL OR t.household_id = $4::BIGINT)
    AND ($5::TIMESTAMPTZ IS NULL OR t.transaction_date >= $5::TIMESTAMPTZ)
    AND ($6::TIMESTAMPTZ IS NULL OR t.transaction_date <= $6::TIMESTAMPTZ)
    AND (
        $7::TEXT IS NULL
        OR t.description ILIKE '%' || $7::TEXT || '%'
        OR t.notes ILIKE '%' || $7::TEXT || '%'
    )
ORDER BY
    CASE WHEN $8::TEXT = 'transaction_date' AND $9::TEXT = 'asc' THEN t.transaction_date END ASC,
    CASE WHEN $8::TEXT = 'transaction_date' AND $9::TEXT = 'desc' THEN t.transaction_date END DESC,
    CASE WHEN $8::TEXT = 'created_at' AND $9::TEXT = 'asc' THEN t.created_at END ASC,
    CASE WHEN $8::TEXT = 'created_at' AND $9::TEXT = 'desc' THEN t.created_at END DESC,
    CASE WHEN $8::TEXT = 'amount' AND $9::TEXT = 'asc' THEN t.amount END ASC,
    CASE WHEN $8::TEXT = 'amount' AND $9::TEXT = 'desc' THEN t.amount END DESC,
    CASE WHEN $8::TEXT = 'id' AND $9::TEXT = 'asc' THEN t.id END ASC,
    CASE WHEN $8::TEXT = 'id' AND $9::TEXT = 'desc' THEN t.id END DESC,
    t.transaction_date DESC,
    t.id DESC
LIMIT $11::INT
OFFSET $10::INT
`

type ListTransactionsParams struct {
	OnlyDeleted    bool               `json:"onlyDeleted"`
	IncludeDeleted bool               `json:"includeDeleted"`
	AuthorID       *int64             `json:"authorId"`
	HouseholdID    *int64             `json:"householdId"`
	FromDate       pgtype.Timestamptz `json:"fromDate"`
	ToDate         pgtype.Timestamptz `json:"toDate"`
	Search         *string            `json:"search"`
	Sort           string             `json:"sort"`
	SortOrder      string             `json:"sortOrder"`
	ResultOffset   int32              `json:"resultOffset"`
	ResultLimit    int32              `json:"resultLimit"`
}

type ListTransactionsRow struct {
	Transaction   Transaction `json:"transaction"`
	AuthorID      int64       `json:"authorId"`
	AuthorName    string      `json:"authorName"`
	HouseholdID   *int64      `json:"householdId"`
	HouseholdName *string     `json:"householdName"`
	CategoryID    *int64      `json:"categoryId"`
	CategoryCode  *string     `json:"categoryCode"`
	CategoryName  *string     `json:"categoryName"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.OnlyDeleted,
		arg.IncludeDeleted,
		arg.AuthorID,
		arg.HouseholdID,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
		arg.Sort,
		arg.SortOrder,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.Amount,
			&i.Transaction.AuthorID,
			&i.Transaction.Description,
			&i.Transaction.TransactionDate,
			&i.Transaction.TransactionID,
			&i.Transaction.HouseholdID,
			&i.Transaction.Notes,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.DeletedAt,
			&i.Transaction.DeletedByUserID,
			&i.Transaction.DeleteReason,
			&i.Transaction.CategoryID,
			&i.AuthorID,
			&i.AuthorName,
			&i.HouseholdID,
			&i.HouseholdName,
			&i.CategoryID,
			&i.CategoryCode,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByHousehold = `-- name: ListTransactionsByHousehold :many
SELECT id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id FROM transaction
WHERE transaction_type=2 AND household_id = $1
`

func (q *Queries) ListTransactionsByHousehold(ctx context.Context, householdID *int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmappedBudgetTransactions = `-- name: ListUnmappedBudgetTransactions :many
SELECT
    t.id,
    t.transaction_date,
    t.description,
    ROUND(t.amount::NUMERIC, 2) AS amount,
    c.id AS category_id,
    c.code AS category_code,
    c.name AS category_name
FROM budget b
JOIN transaction t
    ON t.deleted_at IS NULL
   AND t.transaction_date >= (b.period_start::DATE::TIMESTAMP AT TIME ZONE 'UTC')
   AND t.transaction_date < ((b.period_end::DATE + INTERVAL '1 day')::TIMESTAMP AT TIME ZONE 'UTC')
   AND (
       (b.household_id IS NOT NULL AND t.household_id = b.household_id)
       OR
       (b.user_id IS NOT NULL AND t.author_id = b.user_id AND t.household_id IS NULL)
   )
LEFT JOIN category c ON c.id = t.category_id
WHERE b.id = $1::BIGINT
  AND NOT EXISTS (
      SELECT 1
      FROM budget_line_category blc
      WHERE blc.budget_id = b.id
        AND blc.category_id = t.category_id
  )
ORDER BY t.transaction_date ASC, t.id ASC
`

type ListUnmappedBudgetTransactionsRow struct {
	ID              int64              `json:"id"`
	TransactionDate pgtype.Timestamptz `json:"transactionDate"`
	Description     *string            `json:"description"`
	Amount          pgtype.Numeric     `json:"amount"`
	CategoryID      *int64             `json:"categoryId"`
	CategoryCode    *string            `json:"categoryCode"`
	CategoryName    *string            `json:"categoryName"`
}

func (q *Queries) ListUnmappedBudgetTransactions(ctx context.Context, budgetID int64) ([]ListUnmappedBudgetTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listUnmappedBudgetTransactions, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnmappedBudgetTransactionsRow
	for rows.Next() {
		var i ListUnmappedBudgetTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CategoryCode,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users
ORDER BY name ASC, id ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramID,
			&i.PhoneNumber,
			&i.WhatsappID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransactionsById = `-- name: RestoreTransactionsById :many
UPDATE transaction
SET
    deleted_at = NULL,
    deleted_by_user_id = NULL,
    delete_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ANY($1::BIGINT[])
  AND deleted_at IS NOT NULL
RETURNING id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id
`

func (q *Queries) RestoreTransactionsById(ctx context.Context, ids []int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, restoreTransactionsById, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransactionsById = `-- name: SoftDeleteTransactionsById :many
UPDATE transaction
SET
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by_user_id = $1::BIGINT,
    delete_reason = $2::TEXT,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ANY($3::BIGINT[])
  AND deleted_at IS NULL
RETURNING id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id
`

type SoftDeleteTransactionsByIdParams struct {
	DeletedByUserID int64   `json:"deletedByUserId"`
	DeleteReason    *string `json:"deleteReason"`
	Ids             []int64 `json:"ids"`
}

func (q *Queries) SoftDeleteTransactionsById(ctx context.Context, arg SoftDeleteTransactionsByIdParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, softDeleteTransactionsById, arg.DeletedByUserID, arg.DeleteReason, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUncategorizedBudgetTransactions = `-- name: SumUncategorizedBudgetTransactions :one
SELECT ROUND(COALESCE(SUM(t.amount), 0)::NUMERIC, 2) AS actual_amount
FROM budget b
LEFT JOIN transaction t
    ON t.deleted_at IS NULL
   AND t.category_id IS NULL
   AND t.transaction_date >= (b.period_start::DATE::TIMESTAMP AT TIME ZONE 'UTC')
   AND t.transaction_date < ((b.period_end::DATE + INTERVAL '1 day')::TIMESTAMP AT TIME ZONE 'UTC')
   AND (
       (b.household_id IS NOT NULL AND t.household_id = b.household_id)
       OR
       (b.user_id IS NOT NULL AND t.author_id = b.user_id AND t.household_id IS NULL)
   )
WHERE b.id = $1::BIGINT
GROUP BY b.id
`

func (q *Queries) SumUncategorizedBudgetTransactions(ctx context.Context, budgetID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumUncategorizedBudgetTransactions, budgetID)
	var actual_amount pgtype.Numeric
	err := row.Scan(&actual_amount)
	return actual_amount, err
}

const updateBudgetLine = `-- name: UpdateBudgetLine :one
UPDATE budget_line
SET
    name = CASE
        WHEN $1::bool THEN $2::VARCHAR
        ELSE name
    END,
    allocation_amount = CASE
        WHEN $3::bool THEN $4::NUMERIC
        ELSE allocation_amount
    END,
    sort_order = CASE
        WHEN $5::bool THEN $6::INTEGER
        ELSE sort_order
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7::BIGINT
RETURNING id, budget_id, name, allocation_amount, sort_order, created_at, updated_at
`

type UpdateBudgetLineParams struct {
	SetName             bool           `json:"setName"`
	Name                string         `json:"name"`
	SetAllocationAmount bool           `json:"setAllocationAmount"`
	AllocationAmount    pgtype.Numeric `json:"allocationAmount"`
	SetSortOrder        bool           `json:"setSortOrder"`
	SortOrder           int32          `json:"sortOrder"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateBudgetLine(ctx context.Context, arg UpdateBudgetLineParams) (BudgetLine, error) {
	row := q.db.QueryRow(ctx, updateBudgetLine,
		arg.SetName,
		arg.Name,
		arg.SetAllocationAmount,
		arg.AllocationAmount,
		arg.SetSortOrder,
		arg.SortOrder,
		arg.ID,
	)
	var i BudgetLine
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.Name,
		&i.AllocationAmount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one

UPDATE category
SET
    name = CASE
        WHEN $1::bool THEN $2::VARCHAR
        ELSE name
    END,
    description = CASE
        WHEN $3::bool THEN $4::TEXT
        ELSE description
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5::BIGINT
RETURNING id, code, name, description, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	SetName        bool    `json:"setName"`
	Name           string  `json:"name"`
	SetDescription bool    `json:"setDescription"`
	Description    *string `json:"description"`
	ID             int64   `json:"id"`
}

// WRITES
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageContents = `-- name: UpdateMessageContents :exec
UPDATE llm_message SET contents = $2 WHERE id = $1
`

type UpdateMessageContentsParams struct {
	ID       int64  `json:"id"`
	Contents []byte `json:"contents"`
}

func (q *Queries) UpdateMessageContents(ctx context.Context, arg UpdateMessageContentsParams) error {
	_, err := q.db.Exec(ctx, updateMessageContents, arg.ID, arg.Contents)
	return err
}

const updateTransactionById = `-- name: UpdateTransactionById :one
UPDATE
    transaction
SET
    amount = CASE
        WHEN $3::bool THEN $4::real
        ELSE amount
    END,
    author_id = CASE
        WHEN $5::bool THEN $6::BIGINT
        ELSE author_id
    END,
    category_id = CASE
        WHEN $7::bool THEN $8::BIGINT
        ELSE category_id
    END,
    description = CASE
        WHEN $9::bool THEN $10::text
        ELSE description
    END,
    transaction_date = CASE
        WHEN $11::bool THEN $12::timestamp
        ELSE transaction_date
    END,
    notes = CASE
        WHEN $13::bool THEN $14::text
        ELSE notes
    END,
    household_id = CASE
        WHEN $15::bool THEN $16::BIGINT
        ELSE household_id
    END,
    transaction_id = $2
WHERE
    id = $1 RETURNING id, amount, author_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason, category_id
`

type UpdateTransactionByIdParams struct {
	ID                 int64            `json:"id"`
	TransactionID      string           `json:"transactionId"`
	SetAmount          bool             `json:"setAmount"`
	Amount             float32          `json:"amount"`
	SetAuthorID        bool             `json:"setAuthorId"`
	AuthorID           int64            `json:"authorId"`
	SetCategoryID      bool             `json:"setCategoryId"`
	CategoryID         *int64           `json:"categoryId"`
	SetDescription     bool             `json:"setDescription"`
	Description        *string          `json:"description"`
	SetTransactionDate bool             `json:"setTransactionDate"`
	TransactionDate    pgtype.Timestamp `json:"transactionDate"`
	SetNotes           bool             `json:"setNotes"`
	Notes              *string          `json:"notes"`
	SetHouseholdID     bool             `json:"setHouseholdId"`
	HouseholdID        *int64           `json:"householdId"`
}

func (q *Queries) UpdateTransactionById(ctx context.Context, arg UpdateTransactionByIdParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionById,
		arg.ID,
		arg.TransactionID,
		arg.SetAmount,
		arg.Amount,
		arg.SetAuthorID,
		arg.AuthorID,
		arg.SetCategoryID,
		arg.CategoryID,
		arg.SetDescription,
		arg.Description,
		arg.SetTransactionDate,
		arg.TransactionDate,
		arg.SetNotes,
		arg.Notes,
		arg.SetHouseholdID,
		arg.HouseholdID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
		&i.CategoryID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    discord_id = CASE
        WHEN $1::bool THEN $2::VARCHAR
        ELSE discord_id
    END,
    telegram_id = CASE
        WHEN $3::bool THEN $4::VARCHAR
        ELSE telegram_id
    END,
    phone_number = CASE
        WHEN $5::bool THEN $6::VARCHAR
        ELSE phone_number
    END,
    whatsapp_id = CASE
        WHEN $7::bool THEN $8::VARCHAR
        ELSE whatsapp_id
    END,
    name = CASE
        WHEN $9::bool THEN $10::VARCHAR
        ELSE name
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $11::BIGINT
RETURNING id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id
`

type UpdateUserParams struct {
	SetDiscordID   bool    `json:"setDiscordId"`
	DiscordID      *string `json:"discordId"`
	SetTelegramID  bool    `json:"setTelegramId"`
	TelegramID     *string `json:"telegramId"`
	SetPhoneNumber bool    `json:"setPhoneNumber"`
	PhoneNumber    *string `json:"phoneNumber"`
	SetWhatsappID  bool    `json:"setWhatsappId"`
	WhatsappID     *string `json:"whatsappId"`
	SetName        bool    `json:"setName"`
	Name           string  `json:"name"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.SetDiscordID,
		arg.DiscordID,
		arg.SetTelegramID,
		arg.TelegramID,
		arg.SetPhoneNumber,
		arg.PhoneNumber,
		arg.SetWhatsappID,
		arg.WhatsappID,
		arg.SetName,
		arg.Name,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}
