// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLlmMessage = `-- name: CreateLlmMessage :one
INSERT INTO
    llm_message (session_id, user_id, role, contents, parent_id)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateLlmMessageParams struct {
	SessionID int64  `json:"sessionId"`
	UserID    int64  `json:"userId"`
	Role      string `json:"role"`
	Contents  []byte `json:"contents"`
	ParentID  *int64 `json:"parentId"`
}

// Messages
func (q *Queries) CreateLlmMessage(ctx context.Context, arg CreateLlmMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLlmMessage,
		arg.SessionID,
		arg.UserID,
		arg.Role,
		arg.Contents,
		arg.ParentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLlmSession = `-- name: CreateLlmSession :one
INSERT INTO
    llm_session (user_id, source_id)
VALUES
    ($1, $2) RETURNING id, user_id, source_id, created_at, updated_at
`

type CreateLlmSessionParams struct {
	UserID   int64  `json:"userId"`
	SourceID string `json:"sourceId"`
}

// ******************* LLM *******************
// Session
func (q *Queries) CreateLlmSession(ctx context.Context, arg CreateLlmSessionParams) (LlmSession, error) {
	row := q.db.QueryRow(ctx, createLlmSession, arg.UserID, arg.SourceID)
	var i LlmSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transaction
(
    amount,
    budget_category_id,
    description,
    transaction_date,
    transaction_id,
    author_id,
    household_id,
    notes
)
VALUES
($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason
`

type CreateTransactionParams struct {
	Amount           float32            `json:"amount"`
	BudgetCategoryID *int64             `json:"budgetCategoryId"`
	Description      *string            `json:"description"`
	TransactionDate  pgtype.Timestamptz `json:"transactionDate"`
	TransactionID    string             `json:"transactionId"`
	AuthorID         int64              `json:"authorId"`
	HouseholdID      *int64             `json:"householdId"`
	Notes            *string            `json:"notes"`
}

// WRITES
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.BudgetCategoryID,
		arg.Description,
		arg.TransactionDate,
		arg.TransactionID,
		arg.AuthorID,
		arg.HouseholdID,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.BudgetCategoryID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (discord_id, telegram_id, phone_number, whatsapp_id, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id
`

type CreateUserParams struct {
	DiscordID   *string `json:"discordId"`
	TelegramID  *string `json:"telegramId"`
	PhoneNumber *string `json:"phoneNumber"`
	WhatsappID  *string `json:"whatsappId"`
	Name        string  `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DiscordID,
		arg.TelegramID,
		arg.PhoneNumber,
		arg.WhatsappID,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getActiveSessionBySourceId = `-- name: GetActiveSessionBySourceId :one
SELECT
    id, user_id, source_id, created_at, updated_at
FROM
    llm_session
WHERE
    source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetActiveSessionBySourceId(ctx context.Context, sourceID string) (LlmSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionBySourceId, sourceID)
	var i LlmSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByGuildId = `-- name: GetHouseholdByGuildId :one
SELECT id, name, guild_id, created_at, updated_at from household where guild_id = $1
`

func (q *Queries) GetHouseholdByGuildId(ctx context.Context, guildID string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByGuildId, guildID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GuildID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdById = `-- name: GetHouseholdById :one
SELECT id, name, guild_id, created_at, updated_at FROM household WHERE id = $1
`

func (q *Queries) GetHouseholdById(ctx context.Context, id int64) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdById, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GuildID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByName = `-- name: GetHouseholdByName :one
SELECT id, name, guild_id, created_at, updated_at FROM household WHERE name = $1
`

func (q *Queries) GetHouseholdByName(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByName, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GuildID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdUsers = `-- name: GetHouseholdUsers :many
SELECT u.id, u.discord_id, u.name, u.created_at, u.updated_at, u.telegram_id, u.phone_number, u.whatsapp_id FROM users u
JOIN household_user hu on hu.user_id = u.id
WHERE hu.household_id = $1
`

func (q *Queries) GetHouseholdUsers(ctx context.Context, householdID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getHouseholdUsers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramID,
			&i.PhoneNumber,
			&i.WhatsappID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdByTransactionId = `-- name: GetIdByTransactionId :one
SELECT id FROM transaction
WHERE transaction_id = $1
`

func (q *Queries) GetIdByTransactionId(ctx context.Context, transactionID string) (int64, error) {
	row := q.db.QueryRow(ctx, getIdByTransactionId, transactionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTableAndColumnMetadata = `-- name: GetTableAndColumnMetadata :many

SELECT
  t.table_schema::text AS schema_name,
  t.table_name::text AS table_name,
  COALESCE(obj_description(pgc.oid, 'pg_class'), '')::text AS table_description,
  c.column_name::text AS column_name,
  c.data_type::text AS data_type,
  COALESCE(col_description(pgc.oid, c.ordinal_position), '')::text AS column_description,
  (c.is_nullable = 'YES')::boolean AS is_nullable,
  -- Check if part of any index
  EXISTS (
    SELECT 1
    FROM pg_catalog.pg_index i
    WHERE i.indrelid = pgc.oid
      AND c.ordinal_position = ANY(i.indkey)
  )::boolean AS is_indexed,
  -- Check if part of a unique index
  EXISTS (
    SELECT 1
    FROM pg_catalog.pg_index i
    WHERE i.indrelid = pgc.oid
      AND i.indisunique = true
      AND c.ordinal_position = ANY(i.indkey)
  )::boolean AS is_unique,
  -- 1. Foreign Key in format table.column
  COALESCE(
    (
      SELECT ta.relname || '.' || fa.attname
      FROM pg_catalog.pg_constraint con
      JOIN pg_catalog.pg_class ta ON con.confrelid = ta.oid
      JOIN pg_catalog.pg_attribute fa ON fa.attrelid = con.confrelid AND fa.attnum = ANY(con.confkey)
      WHERE con.conrelid = pgc.oid
        AND con.contype = 'f'
        AND c.ordinal_position = ANY(con.conkey)
      LIMIT 1
    ),
    ''
  )::text AS foreign_key_target,
  -- 3. Primary Key Identity
  EXISTS (
    SELECT 1
    FROM pg_catalog.pg_constraint con
    WHERE con.conrelid = pgc.oid
      AND con.contype = 'p'
      AND c.ordinal_position = ANY(con.conkey)
  )::boolean AS is_primary_key
FROM
  information_schema.tables t
  JOIN pg_catalog.pg_class pgc ON t.table_name = pgc.relname
  JOIN pg_catalog.pg_namespace pgn ON pgc.relnamespace = pgn.oid
  AND t.table_schema = pgn.nspname
  JOIN information_schema.columns c ON t.table_name = c.table_name
  AND t.table_schema = c.table_schema
WHERE
  t.table_schema = 'transactions'
  AND t.table_name = ANY($1::TEXT[])
ORDER BY
  t.table_name,
  c.ordinal_position
`

type GetTableAndColumnMetadataRow struct {
	SchemaName        string `json:"schemaName"`
	TableName         string `json:"tableName"`
	TableDescription  string `json:"tableDescription"`
	ColumnName        string `json:"columnName"`
	DataType          string `json:"dataType"`
	ColumnDescription string `json:"columnDescription"`
	IsNullable        bool   `json:"isNullable"`
	IsIndexed         bool   `json:"isIndexed"`
	IsUnique          bool   `json:"isUnique"`
	ForeignKeyTarget  string `json:"foreignKeyTarget"`
	IsPrimaryKey      bool   `json:"isPrimaryKey"`
}

// ******************* sql metadata *******************
func (q *Queries) GetTableAndColumnMetadata(ctx context.Context, tableNames []string) ([]GetTableAndColumnMetadataRow, error) {
	rows, err := q.db.Query(ctx, getTableAndColumnMetadata, tableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableAndColumnMetadataRow
	for rows.Next() {
		var i GetTableAndColumnMetadataRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.TableDescription,
			&i.ColumnName,
			&i.DataType,
			&i.ColumnDescription,
			&i.IsNullable,
			&i.IsIndexed,
			&i.IsUnique,
			&i.ForeignKeyTarget,
			&i.IsPrimaryKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionById = `-- name: GetTransactionById :one

SELECT id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason FROM transaction
WHERE id = $1
`

// ******************* transaction *******************
// READS
func (q *Queries) GetTransactionById(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.BudgetCategoryID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
	)
	return i, err
}

const getTransactionByIdActive = `-- name: GetTransactionByIdActive :one
SELECT id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason FROM transaction
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByIdActive(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdActive, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.BudgetCategoryID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
	)
	return i, err
}

const getTransactionsById = `-- name: GetTransactionsById :many
SELECT id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason FROM transaction
WHERE id = ANY($1::BIGINT[])
`

func (q *Queries) GetTransactionsById(ctx context.Context, ids []int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsById, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.BudgetCategoryID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByIdActive = `-- name: GetTransactionsByIdActive :many
SELECT id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason FROM transaction
WHERE id = ANY($1::BIGINT[])
  AND deleted_at IS NULL
`

func (q *Queries) GetTransactionsByIdActive(ctx context.Context, ids []int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByIdActive, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.BudgetCategoryID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByDiscordAndHouseholdId = `-- name: GetUserByDiscordAndHouseholdId :one
SELECT u.id, u.discord_id, u.name, u.created_at, u.updated_at, u.telegram_id, u.phone_number, u.whatsapp_id FROM users u
JOIN household_user hu on hu.user_id = u.id
WHERE discord_id = $1 and hu.household_id = $2
`

type GetUserByDiscordAndHouseholdIdParams struct {
	DiscordID   *string `json:"discordId"`
	HouseholdID int64   `json:"householdId"`
}

func (q *Queries) GetUserByDiscordAndHouseholdId(ctx context.Context, arg GetUserByDiscordAndHouseholdIdParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordAndHouseholdId, arg.DiscordID, arg.HouseholdID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByDiscordId = `-- name: GetUserByDiscordId :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordId(ctx context.Context, discordID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordId, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByTelegramId = `-- name: GetUserByTelegramId :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramId(ctx context.Context, telegramID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramId, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserByWhatsappId = `-- name: GetUserByWhatsappId :one
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users WHERE whatsapp_id = $1
`

func (q *Queries) GetUserByWhatsappId(ctx context.Context, whatsappID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWhatsappId, whatsappID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}

const getUserDetailsByDiscordId = `-- name: GetUserDetailsByDiscordId :one

SELECT users.id, users.discord_id, users.name, users.created_at, users.updated_at, users.telegram_id, users.phone_number, users.whatsapp_id, household.id, household.name, household.guild_id, household.created_at, household.updated_at FROM users
JOIN household_user on users.id = household_user.user_id
JOIN household on household_user.household_id = household.id
WHERE users.discord_id = $1
`

type GetUserDetailsByDiscordIdRow struct {
	User      User      `json:"user"`
	Household Household `json:"household"`
}

// ******************* users *******************
// READS
func (q *Queries) GetUserDetailsByDiscordId(ctx context.Context, discordID *string) (GetUserDetailsByDiscordIdRow, error) {
	row := q.db.QueryRow(ctx, getUserDetailsByDiscordId, discordID)
	var i GetUserDetailsByDiscordIdRow
	err := row.Scan(
		&i.User.ID,
		&i.User.DiscordID,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.TelegramID,
		&i.User.PhoneNumber,
		&i.User.WhatsappID,
		&i.Household.ID,
		&i.Household.Name,
		&i.Household.GuildID,
		&i.Household.CreatedAt,
		&i.Household.UpdatedAt,
	)
	return i, err
}

const listHouseholds = `-- name: ListHouseholds :many
SELECT id, name, guild_id, created_at, updated_at FROM household
ORDER BY name ASC, id ASC
`

func (q *Queries) ListHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GuildID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLlmMessagesBySessionId = `-- name: ListLlmMessagesBySessionId :many
SELECT
    m.id, m.session_id, m.parent_id, m.role, m.contents, m.user_id, m.created_at, m.updated_at, u.id, u.discord_id, u.name, u.created_at, u.updated_at, u.telegram_id, u.phone_number, u.whatsapp_id
FROM
    llm_message m
JOIN
    users u on u.id = m.user_id
WHERE
    m.session_id = $1
ORDER BY
    m.created_at ASC
`

type ListLlmMessagesBySessionIdRow struct {
	LlmMessage LlmMessage `json:"llmMessage"`
	User       User       `json:"user"`
}

func (q *Queries) ListLlmMessagesBySessionId(ctx context.Context, sessionID int64) ([]ListLlmMessagesBySessionIdRow, error) {
	rows, err := q.db.Query(ctx, listLlmMessagesBySessionId, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLlmMessagesBySessionIdRow
	for rows.Next() {
		var i ListLlmMessagesBySessionIdRow
		if err := rows.Scan(
			&i.LlmMessage.ID,
			&i.LlmMessage.SessionID,
			&i.LlmMessage.ParentID,
			&i.LlmMessage.Role,
			&i.LlmMessage.Contents,
			&i.LlmMessage.UserID,
			&i.LlmMessage.CreatedAt,
			&i.LlmMessage.UpdatedAt,
			&i.User.ID,
			&i.User.DiscordID,
			&i.User.Name,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.TelegramID,
			&i.User.PhoneNumber,
			&i.User.WhatsappID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id, t.amount, t.author_id, t.budget_category_id, t.description, t.transaction_date, t.transaction_id, t.household_id, t.notes, t.created_at, t.updated_at, t.deleted_at, t.deleted_by_user_id, t.delete_reason,
    u.id AS author_id,
    u.name AS author_name,
    h.id AS household_id,
    h.name AS household_name
FROM transaction t
JOIN users u ON u.id = t.author_id
LEFT JOIN household h ON h.id = t.household_id
WHERE
    (NOT $1::bool OR t.deleted_at IS NOT NULL)
    AND ($2::bool OR $1::bool OR t.deleted_at IS NULL)
    AND ($3::BIGINT IS NULL OR t.author_id = $3::BIGINT)
    AND ($4::BIGINT IS NULL OR t.household_id = $4::BIGINT)
    AND ($5::TIMESTAMPTZ IS NULL OR t.transaction_date >= $5::TIMESTAMPTZ)
    AND ($6::TIMESTAMPTZ IS NULL OR t.transaction_date <= $6::TIMESTAMPTZ)
    AND (
        $7::TEXT IS NULL
        OR t.description ILIKE '%' || $7::TEXT || '%'
        OR t.notes ILIKE '%' || $7::TEXT || '%'
    )
ORDER BY
    CASE WHEN $8::TEXT = 'transaction_date' AND $9::TEXT = 'asc' THEN t.transaction_date END ASC,
    CASE WHEN $8::TEXT = 'transaction_date' AND $9::TEXT = 'desc' THEN t.transaction_date END DESC,
    CASE WHEN $8::TEXT = 'created_at' AND $9::TEXT = 'asc' THEN t.created_at END ASC,
    CASE WHEN $8::TEXT = 'created_at' AND $9::TEXT = 'desc' THEN t.created_at END DESC,
    CASE WHEN $8::TEXT = 'amount' AND $9::TEXT = 'asc' THEN t.amount END ASC,
    CASE WHEN $8::TEXT = 'amount' AND $9::TEXT = 'desc' THEN t.amount END DESC,
    CASE WHEN $8::TEXT = 'id' AND $9::TEXT = 'asc' THEN t.id END ASC,
    CASE WHEN $8::TEXT = 'id' AND $9::TEXT = 'desc' THEN t.id END DESC,
    t.transaction_date DESC,
    t.id DESC
LIMIT $11::INT
OFFSET $10::INT
`

type ListTransactionsParams struct {
	OnlyDeleted    bool               `json:"onlyDeleted"`
	IncludeDeleted bool               `json:"includeDeleted"`
	AuthorID       *int64             `json:"authorId"`
	HouseholdID    *int64             `json:"householdId"`
	FromDate       pgtype.Timestamptz `json:"fromDate"`
	ToDate         pgtype.Timestamptz `json:"toDate"`
	Search         *string            `json:"search"`
	Sort           string             `json:"sort"`
	SortOrder      string             `json:"sortOrder"`
	ResultOffset   int32              `json:"resultOffset"`
	ResultLimit    int32              `json:"resultLimit"`
}

type ListTransactionsRow struct {
	Transaction   Transaction `json:"transaction"`
	AuthorID      int64       `json:"authorId"`
	AuthorName    string      `json:"authorName"`
	HouseholdID   *int64      `json:"householdId"`
	HouseholdName *string     `json:"householdName"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.OnlyDeleted,
		arg.IncludeDeleted,
		arg.AuthorID,
		arg.HouseholdID,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
		arg.Sort,
		arg.SortOrder,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.Amount,
			&i.Transaction.AuthorID,
			&i.Transaction.BudgetCategoryID,
			&i.Transaction.Description,
			&i.Transaction.TransactionDate,
			&i.Transaction.TransactionID,
			&i.Transaction.HouseholdID,
			&i.Transaction.Notes,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.DeletedAt,
			&i.Transaction.DeletedByUserID,
			&i.Transaction.DeleteReason,
			&i.AuthorID,
			&i.AuthorName,
			&i.HouseholdID,
			&i.HouseholdName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByHousehold = `-- name: ListTransactionsByHousehold :many
SELECT id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason FROM transaction
WHERE transaction_type=2 AND household_id = $1
`

func (q *Queries) ListTransactionsByHousehold(ctx context.Context, householdID *int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.BudgetCategoryID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id FROM users
ORDER BY name ASC, id ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramID,
			&i.PhoneNumber,
			&i.WhatsappID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransactionsById = `-- name: RestoreTransactionsById :many
UPDATE transaction
SET
    deleted_at = NULL,
    deleted_by_user_id = NULL,
    delete_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ANY($1::BIGINT[])
  AND deleted_at IS NOT NULL
RETURNING id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason
`

func (q *Queries) RestoreTransactionsById(ctx context.Context, ids []int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, restoreTransactionsById, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.BudgetCategoryID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransactionsById = `-- name: SoftDeleteTransactionsById :many
UPDATE transaction
SET
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by_user_id = $1::BIGINT,
    delete_reason = $2::TEXT,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ANY($3::BIGINT[])
  AND deleted_at IS NULL
RETURNING id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason
`

type SoftDeleteTransactionsByIdParams struct {
	DeletedByUserID int64   `json:"deletedByUserId"`
	DeleteReason    *string `json:"deleteReason"`
	Ids             []int64 `json:"ids"`
}

func (q *Queries) SoftDeleteTransactionsById(ctx context.Context, arg SoftDeleteTransactionsByIdParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, softDeleteTransactionsById, arg.DeletedByUserID, arg.DeleteReason, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.AuthorID,
			&i.BudgetCategoryID,
			&i.Description,
			&i.TransactionDate,
			&i.TransactionID,
			&i.HouseholdID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContents = `-- name: UpdateMessageContents :exec
UPDATE llm_message SET contents = $2 WHERE id = $1
`

type UpdateMessageContentsParams struct {
	ID       int64  `json:"id"`
	Contents []byte `json:"contents"`
}

func (q *Queries) UpdateMessageContents(ctx context.Context, arg UpdateMessageContentsParams) error {
	_, err := q.db.Exec(ctx, updateMessageContents, arg.ID, arg.Contents)
	return err
}

const updateTransactionById = `-- name: UpdateTransactionById :one
UPDATE
    transaction
SET
    amount = CASE
        WHEN $3::bool THEN $4::real
        ELSE amount
    END,
    author_id = CASE
        WHEN $5::bool THEN $6::BIGINT
        ELSE author_id
    END,
    budget_category_id = CASE
        WHEN $7::bool THEN $8::BIGINT
        ELSE budget_category_id
    END,
    description = CASE
        WHEN $9::bool THEN $10::text
        ELSE description
    END,
    transaction_date = CASE
        WHEN $11::bool THEN $12::timestamp
        ELSE transaction_date
    END,
    notes = CASE
        WHEN $13::bool THEN $14::text
        ELSE notes
    END,
    household_id = CASE
        WHEN $15::bool THEN $16::BIGINT
        ELSE household_id
    END,
    transaction_id = $2
WHERE
    id = $1 RETURNING id, amount, author_id, budget_category_id, description, transaction_date, transaction_id, household_id, notes, created_at, updated_at, deleted_at, deleted_by_user_id, delete_reason
`

type UpdateTransactionByIdParams struct {
	ID                  int64            `json:"id"`
	TransactionID       string           `json:"transactionId"`
	SetAmount           bool             `json:"setAmount"`
	Amount              float32          `json:"amount"`
	SetAuthorID         bool             `json:"setAuthorId"`
	AuthorID            int64            `json:"authorId"`
	SetBudgetCategoryID bool             `json:"setBudgetCategoryId"`
	BudgetCategoryID    *int64           `json:"budgetCategoryId"`
	SetDescription      bool             `json:"setDescription"`
	Description         *string          `json:"description"`
	SetTransactionDate  bool             `json:"setTransactionDate"`
	TransactionDate     pgtype.Timestamp `json:"transactionDate"`
	SetNotes            bool             `json:"setNotes"`
	Notes               *string          `json:"notes"`
	SetHouseholdID      bool             `json:"setHouseholdId"`
	HouseholdID         *int64           `json:"householdId"`
}

func (q *Queries) UpdateTransactionById(ctx context.Context, arg UpdateTransactionByIdParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionById,
		arg.ID,
		arg.TransactionID,
		arg.SetAmount,
		arg.Amount,
		arg.SetAuthorID,
		arg.AuthorID,
		arg.SetBudgetCategoryID,
		arg.BudgetCategoryID,
		arg.SetDescription,
		arg.Description,
		arg.SetTransactionDate,
		arg.TransactionDate,
		arg.SetNotes,
		arg.Notes,
		arg.SetHouseholdID,
		arg.HouseholdID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AuthorID,
		&i.BudgetCategoryID,
		&i.Description,
		&i.TransactionDate,
		&i.TransactionID,
		&i.HouseholdID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.DeleteReason,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    discord_id = CASE
        WHEN $1::bool THEN $2::VARCHAR
        ELSE discord_id
    END,
    telegram_id = CASE
        WHEN $3::bool THEN $4::VARCHAR
        ELSE telegram_id
    END,
    phone_number = CASE
        WHEN $5::bool THEN $6::VARCHAR
        ELSE phone_number
    END,
    whatsapp_id = CASE
        WHEN $7::bool THEN $8::VARCHAR
        ELSE whatsapp_id
    END,
    name = CASE
        WHEN $9::bool THEN $10::VARCHAR
        ELSE name
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $11::BIGINT
RETURNING id, discord_id, name, created_at, updated_at, telegram_id, phone_number, whatsapp_id
`

type UpdateUserParams struct {
	SetDiscordID   bool    `json:"setDiscordId"`
	DiscordID      *string `json:"discordId"`
	SetTelegramID  bool    `json:"setTelegramId"`
	TelegramID     *string `json:"telegramId"`
	SetPhoneNumber bool    `json:"setPhoneNumber"`
	PhoneNumber    *string `json:"phoneNumber"`
	SetWhatsappID  bool    `json:"setWhatsappId"`
	WhatsappID     *string `json:"whatsappId"`
	SetName        bool    `json:"setName"`
	Name           string  `json:"name"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.SetDiscordID,
		arg.DiscordID,
		arg.SetTelegramID,
		arg.TelegramID,
		arg.SetPhoneNumber,
		arg.PhoneNumber,
		arg.SetWhatsappID,
		arg.WhatsappID,
		arg.SetName,
		arg.Name,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.PhoneNumber,
		&i.WhatsappID,
	)
	return i, err
}
