// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Budget struct {
	ID          int32
	UserID      sql.NullInt32
	HouseholdID sql.NullInt32
	Type        string
}

type BudgetCategory struct {
	ID           int32
	BudgetID     sql.NullInt32
	CategoryName string
	Allocation   float64
}

type Household struct {
	ID   int32
	Name string
}

type HouseholdTransaction struct {
	ID               int32
	PaidBy           sql.NullInt32
	Amount           float64
	IsPaid           bool
	AmountOwed       sql.NullFloat64
	BudgetCategoryID sql.NullInt32
	HouseholdID      sql.NullInt32
}

type HouseholdUser struct {
	HouseholdID sql.NullInt32
	UserID      sql.NullInt32
}

type PersonalTransaction struct {
	ID               int32
	UserID           sql.NullInt32
	BudgetCategoryID sql.NullInt32
}

type User struct {
	ID        int32
	DiscordID sql.NullString
	Name      string
}
