// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID          int32              `json:"id"`
	UserID      *int32             `json:"user_id"`
	HouseholdID *int32             `json:"household_id"`
	Type        string             `json:"type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BudgetCategory struct {
	ID           int32              `json:"id"`
	BudgetID     *int32             `json:"budget_id"`
	CategoryName string             `json:"category_name"`
	Allocation   float32            `json:"allocation"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Household struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HouseholdUser struct {
	HouseholdID int32              `json:"household_id"`
	UserID      int32              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID               int32              `json:"id"`
	Amount           float32            `json:"amount"`
	PaidBy           int32              `json:"paid_by"`
	AmountOwed       *float32           `json:"amount_owed"`
	BudgetCategoryID *int32             `json:"budget_category_id"`
	Description      *string            `json:"description"`
	TransactionDate  pgtype.Timestamptz `json:"transaction_date"`
	TransactionID    *string            `json:"transaction_id"`
	TransactionType  *int32             `json:"transaction_type"`
	Notes            *string            `json:"notes"`
	OwedBy           *int32             `json:"owed_by"`
	HouseholdID      *int32             `json:"household_id"`
	IsPaid           *bool              `json:"is_paid"`
	PaymentDate      pgtype.Timestamptz `json:"payment_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int32              `json:"id"`
	DiscordID *string            `json:"discord_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
