// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionsBudget struct {
	ID          int32
	UserID      *int32
	HouseholdID *int32
	Type        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TransactionsBudgetCategory struct {
	ID           int32
	BudgetID     *int32
	CategoryName string
	Allocation   float32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TransactionsHousehold struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TransactionsHouseholdUser struct {
	HouseholdID int32
	UserID      int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TransactionsTransaction struct {
	ID               int32
	Amount           float32
	PaidBy           int32
	AmountOwed       *float32
	BudgetCategoryID *int32
	Description      *string
	TransactionDate  pgtype.Timestamptz
	TransactionID    *string
	TransactionType  *int32
	OwedBy           *int32
	HouseholdID      *int32
	IsPaid           *bool
	PaymentDate      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TransactionsUser struct {
	ID        int32
	DiscordID *string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
