// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
)

const getHouseholdTransaction = `-- name: GetHouseholdTransaction :one
SELECT id, paid_by, amount, is_paid, amount_owed, budget_category_id, household_id FROM household_transaction
WHERE id = ? LIMIT 1
`

func (q *Queries) GetHouseholdTransaction(ctx context.Context, id int32) (HouseholdTransaction, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdTransaction, id)
	var i HouseholdTransaction
	err := row.Scan(
		&i.ID,
		&i.PaidBy,
		&i.Amount,
		&i.IsPaid,
		&i.AmountOwed,
		&i.BudgetCategoryID,
		&i.HouseholdID,
	)
	return i, err
}
